# Generated by Django 4.0.6 on 2022-07-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_ordered_date_alter_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
    ]
